"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Box,Footprints,ArrowUp,ArrowDown,ArrowLeft,ArrowRight,RotateCcw,Maximize,X,HelpCircle,ChevronRight,Sun,Moon,MapPin,House} from 'lucide-react';
import type {ApartmentController,ViewState} from './space';
const rooms=[['living','リビング・ダイニング','LIVING & DINING'],['bedroom','寝室','BEDROOM'],['closet','ウォークインクローゼット','WALK-IN CLOSET'],['entry','玄関・廊下','ENTRANCE'],['wash','洗面室','POWDER ROOM'],['bath','浴室','BATHROOM'],['toilet','トイレ','RESTROOM'],['balcony','バルコニー','BALCONY']];
export default function Home(){
 const mount=useRef<HTMLDivElement>(null),api=useRef<ApartmentController|null>(null);
 const [state,setState]=useState<ViewState>({mode:'overview',room:'living',x:-.5,z:4.7,yaw:0,night:false}),[ready,setReady]=useState(false),[error,setError]=useState(''),[help,setHelp]=useState(false),[map,setMap]=useState(true);
 useEffect(()=>{let cancelled=false;import('./space').then(({createApartment})=>{if(cancelled||!mount.current)return;api.current=createApartment(mount.current,setState);setReady(true)}).catch(()=>setError('3D表示を開始できませんでした。WebGLに対応したブラウザで再読み込みしてください。'));return()=>{cancelled=true;api.current?.dispose();api.current=null}},[]);
 const walk=(id='living')=>api.current?.goTo(id);
 const hold=(d:string)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);api.current?.hold(d,true)},onPointerUp:()=>api.current?.hold(d,false),onPointerCancel:()=>api.current?.hold(d,false),onLostPointerCapture:()=>api.current?.hold(d,false)});
 return <main className="experience">
 <header className="topbar"><div className="brand"><span className="brand-icon"><House size={22}/></span><div><span className="brand-name">住まいを歩く<span>.</span></span><small>APARTMENT EXPLORER</small></div></div><div className="view-switch" aria-label="表示モード"><button disabled={!ready} aria-pressed={state.mode==='overview'} onClick={()=>api.current?.overview()}><Box size={17}/><span>全体を見る</span></button><button disabled={!ready} aria-pressed={state.mode==='walk'} onClick={()=>walk(state.room)}><Footprints size={17}/><span>室内を歩く</span></button></div><button className="icon-button" aria-label="操作ガイド" onClick={()=>setHelp(true)}><HelpCircle size={21}/></button></header>
 <div className="workspace"><aside className="sidebar"><div className="project-title"><p className="eyebrow">VIRTUAL HOME TOUR</p><h1>光と木の、<br/>心地よい住まい。</h1><p className="project-meta">1LDK ＋ WALK-IN CLOSET</p></div><div className="room-heading"><span>部屋を選ぶ</span><small>08 SPACES</small></div><nav className="room-list" aria-label="部屋への移動">{rooms.map(([id,name,en],i)=><button disabled={!ready} key={id} className={'room '+(state.mode==='walk'&&state.room===id?'active':'')} onClick={()=>walk(id)}><span className="room-number">0{i+1}</span><span className="room-title"><strong>{name}</strong><small>{en}</small></span><ChevronRight size={15}/></button>)}</nav><p className="reference-note">参考画像から再現した3D空間です。<br/>寸法・家具の形状はイメージです。</p></aside>
 <section className="viewport" aria-label="操作できる3D住空間"><div className="scene" ref={mount}/><div className="view-label"><i/><span>{state.mode==='overview'?'DOLLHOUSE VIEW':'WALKTHROUGH'}</span><b/><span>{state.mode==='overview'?'住まいの全体像':rooms.find(r=>r[0]===state.room)?.[1]}</span></div><div className="scene-tools"><button disabled={!ready} className="tool" onClick={()=>api.current?.toggleNight()} aria-label={state.night?'昼の光にする':'夜の光にする'}>{state.night?<Moon size={19}/>:<Sun size={19}/>}</button><button disabled={!ready} className="tool" onClick={()=>api.current?.reset()} aria-label="視点をリセット"><RotateCcw size={18}/></button><button className="tool" onClick={async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{setError('このブラウザでは全画面表示を利用できません。通常表示でお楽しみください。')}}} aria-label="全画面表示"><Maximize size={18}/></button></div>
 {!ready&&!error&&<div className="loading"><i/>住まいを準備しています</div>}{error&&<div className="error" role="alert">{error}<button onClick={()=>location.reload()}>再読み込み</button></div>}{state.mode==='walk'&&<div className="crosshair" aria-hidden="true"/>}
 {map&&<div className="minimap"><div className="map-heading"><span>FLOOR PLAN</span><button aria-label="間取り図を閉じる" onClick={()=>setMap(false)}><X size={15}/></button></div><svg viewBox="0 0 130 230" role="img" aria-label="間取りと現在位置"><g transform="translate(5 8)"><path d="M0 0H120V214H0Z" fill="#e9e6dd" stroke="#6a716d" strokeWidth="2"/><path d="M0 0H44V48H0M44 0V38.4H80V0M80 38.4H120M80 38.4V67.2H120M0 67.2H77V192M77 67.2H120M77 99.2H120M0 192H120" fill="none" stroke="#8f948c" strokeWidth="2"/><path d="M56 67.2H74M77 111V126M83 99.2H104M48 38.4H66M80 25V38" stroke="#e9e6dd" strokeWidth="4"/><rect x="5" y="100" width="29" height="12" fill="#c4c1b6"/><rect x="40" y="140" width="17" height="39" rx="2" fill="#c4c1b6"/><rect x="93" y="147" width="20" height="42" rx="2" fill="#c4c1b6"/><text x="30" y="130">LDK</text><text x="98" y="136">寝室</text><text x="98" y="87">WIC</text><text x="100" y="21">浴室</text><text x="62" y="21">洗面</text><text x="22" y="21">玄関</text><text x="99" y="57">WC</text><text x="60" y="206">バルコニー</text>{state.mode==='walk'&&<g transform={`translate(${(state.x+3)*20} ${(state.z+6)*16}) rotate(${-state.yaw*180/Math.PI})`}><path d="M0 0L-8 -14Q0 -19 8 -14Z" fill="#b9754330"/><circle r="4" fill="#bd7042" stroke="white" strokeWidth="1.5"/></g>}</g></svg><div className="map-caption"><i/>{state.mode==='walk'?'現在地':'間取りイメージ'}</div></div>}
 {!map&&<button className="map-reopen tool" onClick={()=>setMap(true)}><MapPin size={17}/>間取り図</button>}
 <div className="bottom-controls">{state.mode==='overview'?<><div className="scene-hint"><span className="mouse-icon"/>ドラッグで回転 <span>/</span> スクロールで拡大</div><button disabled={!ready} className="enter-button" onClick={()=>walk()}><Footprints size={19}/>室内を歩きはじめる<ArrowUpRight size={18}/></button></>:<><div className="scene-hint walk-hint"><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd>で移動 <span>/</span> ドラッグで見回す</div><button className="lock-button" onClick={()=>api.current?.lockPointer()}>マウスで自由に見回す<ArrowUpRight size={15}/></button></>}</div>
 {state.mode==='walk'&&<div className="touch-pad" aria-label="移動操作"><button aria-label="前へ移動" {...hold('forward')}><ArrowUp size={21}/></button><div><button aria-label="左へ移動" {...hold('left')}><ArrowLeft size={21}/></button><button aria-label="後ろへ移動" {...hold('back')}><ArrowDown size={21}/></button><button aria-label="右へ移動" {...hold('right')}><ArrowRight size={21}/></button></div></div>}<span className="corner-coordinate">{state.mode==='overview'?'01 / RESIDENCE':'EYE LEVEL / 1.60 m'}</span></section></div>
 {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="guide" role="dialog" aria-modal="true" aria-labelledby="guide-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setHelp(false)}}><button autoFocus className="close-guide icon-button" aria-label="操作ガイドを閉じる" onClick={()=>setHelp(false)}><X/></button><p className="eyebrow">HOW TO EXPLORE</p><h2 id="guide-title">自分のペースで、住まいを体験。</h2><dl><dt>全体を見る</dt><dd>ドラッグで回転、ホイールやピンチで拡大・縮小できます。</dd><dt>室内を歩く</dt><dd>W・A・S・D または矢印キーで移動。画面をドラッグして見回します。Shift を押すと速く歩けます。</dd><dt>マウスで自由に見回す</dt><dd>ボタンを押すとマウスが視点に連動します。Esc で解除します。</dd><dt>スマートフォン</dt><dd>画面をスワイプして見回し、矢印ボタンを長押しして歩きます。</dd><dt>部屋へ移動</dt><dd>部屋名を選ぶとその部屋に移動できます。壁や家具の手前で止まります。</dd></dl><button className="enter-button" onClick={()=>setHelp(false)}>探索に戻る<ArrowUpRight size={17}/></button></section></div>}
 </main>
}

